version: "3.3"
services:
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    networks:
      base:
        aliases:
          - frontend

  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    # environment:
    ports:
      - '3001:3000'
    volumes:
      - ./backend:/app
    networks:
      base:
        aliases:
          - backend
volumes:
  fe_node_modules:
  be_node_modules:
  db_data:

networks:
  base:
