version: "3.3"
services:
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - fe_node_modules:/app/node_modules

  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    volumes:
      - ./backend:/app
      - be_node_modules:/app/node_modules

volumes:
  fe_node_modules:
  be_node_modules:
