version: "3.3"
services:
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - fe_node_modules:/app/node_modules

  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    environment:
      - FIREBASE_API_KEY: ${FIREBASE_API_KEY}
      - FIREBASE_AUTH_DOMAIN: ${FIREBASE_AUTH_DOMAIN}
      - FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET}
      - FIREBASE_MESSAGING_SENDER_ID: ${FIREBASE_MESSAGING_SENDER_ID}
      - FIREBASE_APP_ID: ${FIREBASE_APP_ID}
      - FIREBASE_MEASUREMENT_ID: ${FIREBASE_MEASUREMENT_ID}
      - FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      - SENDER_EMAIL: ${SENDER_EMAIL}
      - SENDER_EMAIL_PASSWORD: ${SENDER_EMAIL_PASSWORD}
      - REVIEWS_DESTINATION_EMAIL: ${REVIEWS_DESTINATION_EMAIL}
      - ALGOLIA_APPLICATION_ID: ${ALGOLIA_APPLICATION_ID}
      - ALGOLIA_API_KEY: ${ALGOLIA_API_KEY}
    ports:
      - '3001:3000'
    volumes:
      - ./backend:/app
      - be_node_modules:/app/node_modules


volumes:
  fe_node_modules:
  be_node_modules:
