version: "3.3"
services:
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app

  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    volumes:
      - ./backend:/app
