name: Backend
on: [pull_request]

env:
  FIREBASE_API_KEY: ${{secrets.FIREBASE_API_KEY}}
  FIREBASE_AUTH_DOMAIN: ${{secrets.FIREBASE_AUTH_DOMAIN}}
  FIREBASE_STORAGE_BUCKET: ${{secrets.FIREBASE_STORAGE_BUCKET}}
  FIREBASE_MESSAGING_SENDER_ID: ${{secrets.FIREBASE_MESSAGING_SENDER_ID}}
  FIREBASE_APP_ID: ${{secrets.FIREBASE_APP_ID}}
  FIREBASE_MEASUREMENT_ID: ${{secrets.FIREBASE_MEASUREMENT_ID}}
  FIREBASE_PROJECT_ID: ${{secrets.FIREBASE_PROJECT_ID}}
  SENDER_EMAIL: ${{secrets.SENDER_EMAIL}}
  SENDER_EMAIL_PASSWORD: ${{secrets.SENDER_EMAIL_PASSWORD}}
  REVIEWS_DESTINATION_EMAIL: ${{secrets.REVIEWS_DESTINATION_EMAIL}}
  ALGOLIA_APPLICATION_ID: ${{secrets.ALGOLIA_APPLICATION_ID}}
  ALGOLIA_API_KEY: ${{secrets.ALGOLIA_API_KEY}}

jobs:
  build-and-lint:
    name: Build and Lint
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      
    - name: npm install
      run: npm install
    - name: lint
      run: npm run lint
    - name: test
      run: npm run test --if-present