name: Backend
on: [pull_request]

jobs:
  build-and-lint:
    name: Build and Lint
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      
    - name: npm install
      run: npm install
    - name: lint
      run: npm run lint
    - name: test
      run: npm run test --if-present